### ISSUE TITLE
Please, create a simple ReadME

### ISSUE THREAD

**Issue by qPCR4vir** [cnjinhao/nana-docs#1]
Hy,
I'm working on the doxygen project, but its seems that I can not fork an empty repository and then can not make a pull request. The same for the demos.
Thank

**Comment by cnjinhao** [comment]
The best way is to create a repo for docs in your account, and then I will clone it.

**Comment by qPCR4vir** [comment]
You were faster than I.
I created a nana-demo repository with old examples. I will test and update it againg.
